name: Dependency Review

on:
  pull_request:
    branches:
      - main
      - master
      - develop
      - release/*

permissions:
  contents: read
  pull-requests: write   

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # This action compares the dependencies in the PR
      # against the base branch and checks for vulnerabilities
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
          comment-summary-in-pr: true
